services:
  postgres:
    image: postgres:latest
    container_name: postgres-product-db
    environment:
      POSTGRES_USER: productAdmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
